In [2]:
import pandas as pd

races = pd.read_csv("f1_races_2000_2026.csv")

results = pd.read_csv("f1_race_results_2000_2026.csv")

qualifying = pd.read_csv("f1_qualifying_2000_2026.csv")

drivers = pd.read_csv("f1_driver_standings_2000_2026.csv")

constructors = pd.read_csv("f1_constructor_standings_2000_2026.csv")

In [3]:
drivers.head()

,season,driver_id,driver_name,nationality,constructor,position,points,wins
0,2000,michael_schumacher,Michael Schumacher,German,Ferrari,1.0,108.0,9
1,2000,hakkinen,Mika Häkkinen,Finnish,McLaren,2.0,89.0,4
2,2000,coulthard,David Coulthard,British,McLaren,3.0,73.0,3
3,2000,barrichello,Rubens Barrichello,Brazilian,Ferrari,4.0,62.0,1
4,2000,ralf_schumacher,Ralf Schumacher,German,Williams,5.0,24.0,0

In [4]:
drivers["performance_score"] = (
    drivers["points"] +
    (drivers["wins"] * 5)
)

drivers[
    ["driver_name", "points", "wins", "performance_score"]
].head()

          driver_name  points  wins  performance_score
0  Michael Schumacher   108.0     9              153.0
1       Mika Häkkinen    89.0     4              109.0
2     David Coulthard    73.0     3               88.0
3  Rubens Barrichello    62.0     1               67.0
4     Ralf Schumacher    24.0     0               24.0

In [5]:
print(drivers.shape)
print(results.shape)
print(qualifying.shape)

(370, 9)
(2666, 18)
(2515, 11)

In [6]:
drivers["performance_score"] = (
    drivers["points"] +
    (drivers["wins"] * 5)
)

top_drivers = drivers.sort_values(
    "performance_score",
    ascending=False
)

top_drivers[
    ["driver_name","points","wins","performance_score"]
].head(10)

          driver_name  points  wins  performance_score
275  Sebastian Vettel   392.0    11              447.0
327    Max Verstappen   395.5    10              445.5
304    Lewis Hamilton   380.0    10              430.0
303      Nico Rosberg   385.0     9              430.0
328    Lewis Hamilton   387.5     8              427.5
276     Jenson Button   270.0     3              285.0
248  Sebastian Vettel   256.0     5              281.0
249   Fernando Alonso   252.0     5              277.0
277       Mark Webber   258.0     1              263.0
278   Fernando Alonso   257.0     1              262.0

In [7]:
constructors["dominance_score"] = (
    constructors["points"] +
    (constructors["wins"] * 5)
)

constructors.sort_values(
    "dominance_score",
    ascending=False
)[
    ["constructor","points","wins","dominance_score"]
].head(10)

   constructor  points  wins  dominance_score
42    Red Bull     759    17              844
32    Mercedes     668    12              728
21    Red Bull     596    13              661
43     Ferrari     554     4              574
33     Ferrari     522     5              547
44    Mercedes     515     1              520
34    Red Bull     368     3              383
22    Mercedes     360     3              375
23     Ferrari     354     2              364
24    Lotus F1     315     1              320

In [8]:
pole_positions = qualifying[
    qualifying["position"] == 1
]

pole_count = (
    pole_positions
    .groupby("driver_name")
    .size()
    .reset_index(name="pole_positions")
    .sort_values(
        "pole_positions",
        ascending=False
    )
)

pole_count.head(10)

           driver_name  pole_positions
10      Lewis Hamilton              29
19    Sebastian Vettel              15
13  Michael Schumacher              13
12      Max Verstappen              12
21     Valtteri Bottas               7
15        Nico Rosberg               7
1      Charles Leclerc               7
2         Felipe Massa               5
3      Fernando Alonso               5
7        Jenson Button               5

In [9]:
results["fastest_lap_speed"] = pd.to_numeric(
    results["fastest_lap_speed"],
    errors="coerce"
)

fastest_drivers = (
    results.groupby("driver_name")
    ["fastest_lap_speed"]
    .mean()
    .reset_index()
    .sort_values(
        "fastest_lap_speed",
        ascending=False
    )
)

fastest_drivers.head(10)

           driver_name  fastest_lap_speed
83      Oliver Bearman         241.103000
36         Guanyu Zhou         218.114533
2      Alexander Albon         216.652750
82       Nyck de Vries         216.467200
85       Oscar Piastri         215.836600
50  Juan Pablo Montoya         214.502167
13     Charles Leclerc         214.191182
60        Lando Norris         213.905962
31      George Russell         213.566067
63      Logan Sargeant         213.182375

In [10]:
driver_speed_stats = (
    results.groupby("driver_name")
    .agg(
        avg_speed=("fastest_lap_speed","mean"),
        races=("fastest_lap_speed","count")
    )
)

driver_speed_stats = driver_speed_stats[
    driver_speed_stats["races"] >= 10
]

driver_speed_stats.sort_values(
    "avg_speed",
    ascending=False
)

                       avg_speed  races
driver_name
Guanyu Zhou           218.114533     15
Alexander Albon       216.652750     24
Juan Pablo Montoya    214.502167     12
Charles Leclerc       214.191182     33
Lando Norris          213.905962     26
George Russell        213.566067     30
Esteban Ocon          212.929088     34
Pierre Gasly          212.490697     33
Max Verstappen        211.924937     48
Lance Stroll          211.678538     39
Ralf Schumacher       211.422056     18
Nicholas Latifi       211.098214     14
Yuki Tsunoda          210.559111     18
David Coulthard       210.133565     23
Antonio Giovinazzi    209.449000     16
Kevin Magnussen       209.438977     43
Jacques Villeneuve    209.359200     10
Christian Klien       208.361455     11
Valtteri Bottas       208.258897     58
Carlos Sainz          208.233255     47
Takuma Sato           207.981300     20
Lewis Hamilton        207.136333     87
Sergio Pérez          206.605723     65
Michael Schumacher    205.832966     29
Daniel Ricciardo      205.471893     56
Fernando Alonso       205.424622     90
Giancarlo Fisichella  205.320321     28
Tiago Monteiro        205.250200     10
Mark Webber           205.228565     46
Jarno Trulli          204.794941     34
Rubens Barrichello    204.751757     37
Nick Heidfeld         204.689829     35
Kimi Räikkönen        204.610128     78
Nico Hülkenberg       204.605755     49
Stoffel Vandoorne     203.984600     10
Daniil Kvyat          203.634185     27
Vitantonio Liuzzi     203.547937     16
Christijan Albers     202.961636     11
Sebastian Vettel      202.650254     67
Felipe Massa          202.619031     65
Jenson Button         201.973328     58
Robert Kubica         201.721826     23
Romain Grosjean       201.293487     39
Heikki Kovalainen     199.842292     24
Nico Rosberg          199.732294     51
Paul di Resta         199.192000     13
Sébastien Buemi       198.997000     10
Narain Karthikeyan    198.295182     11
Jean-Éric Vergne      197.584500     12
Marcus Ericsson       197.420208     24
Adrian Sutil          197.063577     26
Timo Glock            196.671056     18
Vitaly Petrov         196.456833     12
Esteban Gutiérrez     196.248929     14
Kamui Kobayashi       195.776786     14
Pastor Maldonado      195.091619     21